### ISSUE TITLE
Build fails on demos

### ISSUE THREAD

**Issue by DePasqualeOrg** [umaranis/svelte-lexical#1]
When I run `npm build` on the demos, I get errors like the following:

`[!] Error: 'PlainTextPlugin' is not exported by node_modules/svelte-lexical/src/index.js, imported by src/App.svelte`

`[!] Error: 'RichTextBasicComposer' is not exported by node_modules/svelte-lexical/src/index.js, imported by src/App.svelte`

The demo works when I run `pnpm -C demos/richtext-editor dev`, as noted in the readme, but ideally I'd like to just drag and drop the relevant demo source files into a SvelteKit project, after running `npm i svelte-lexical` on that project. But when I do that, I get an error message like the above.

**Comment by umaranis** [comment]
Hi @DePasqualeOrg ,

This is because the package.json for demos is referring to the older version of svelte-lexical npm package.

In package.json, update `"svelte-lexical": "^0.1.2-beta.1"` to `"svelte-lexical": "^0.1.2-beta.2"` to resolve the issue.
