### ISSUE TITLE
sveltekit demos don't work

### ISSUE THREAD

**Issue by Shrimp22** [umaranis/svelte-lexical#11]
Hello I am getting issue when I want to use svelte-lexical with svelte kit also I tried to use example from demos and still getting the same error 
![image](https://user-images.githubusercontent.com/86841678/205448750-f23398d2-0c73-4c2c-a91a-61b16e6b67f0.png)

**Comment by umaranis** [comment]
Hi @Shrimp22 ,
I have fixed the `sveltekit` demo. It should work now.
The problem was not understanding the typescript files after recent port to svelte-lexical to typescript.

If you are looking for a working version of `svelte` (not kit), then you can `playground`.

PS: fixed by 31cafa4

**Comment by Shrimp22** [comment]
Is works now for me thank you so much for your help!
