### ISSUE TITLE
Feature request: `CollaborationPlugin`

### ISSUE THREAD

**Issue by joakim** [umaranis/svelte-lexical#19]
Thanks for making Lexical available to Svelte!

I can understand if this will take a lower priority, but I'd love to see support for the `<CollaborationPlugin>`. [Yjs](https://beta.yjs.dev/) makes realtime collaboration and offline storage very easy, and Lexical has support for Yjs out of the box:

https://lexical.dev/docs/collaboration/react

If it's relatively straight forward, I could give it a try myself. If so, I would just need some pointers to get started. I'm familiar with Svelte, but not yet with Lexical.

**Comment by umaranis** [comment]
Hi @joakim ,
I have been focusing on the core editor features and have been avoiding the work of collaboration. We have made significant progress but I still have work to do with a number of plugins.

I would really appreciate it if you could assist with implementing the `CollaborationPlugin`. I believe, the first step would be to have a working version of collaboration in lexical itself. I can't find it in the playground. 

If you are able to contribute I would suggest starting with building a collaborative editor in `React Lexical`. The link you shared above is a good starting point.

**Comment by joakim** [comment]
Nice, thank you! Collaboration is a big part of my project, so I really appreciate this. I'll definitely move over to svelte-lexical, as soon as I have the time :)
