### ISSUE TITLE
Support for server-side-rendering

### ISSUE THREAD

**Issue by YugoCode** [umaranis/svelte-lexical#22]
First of all thanks for all the effort! ❤️  This might be the goto Svelte component for any developer who needs a rich text editor :) 

I'm using SvelteKit and have to operate my app with SSR. I get following error:

> XXX is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules. Otherwise you may need to fix a XXX.

I have seen this comment [here](https://github.com/umaranis/svelte-lexical/blob/master/demos/sveltekit/src/routes/%2Bpage.js): 
```
//TODO: initializeEditor references `document` which causes the server-side-rendering to fail
export const ssr = false;
```

Is SSR supported by lexical and is that something you could add support for as well?

Would really appreciate it and I think many other devs as well :)

**Comment by umaranis** [comment]
Hey @YugoCode ,
I have implemented support for SSR. (cd1bf3f)

Do try it out and provide your feedback.

**Comment by YugoCode** [comment]
Thanks, no error anymore! :)
