### ISSUE TITLE
Design a logo for svelte-lexical

### ISSUE THREAD

**Issue by umaranis** [umaranis/svelte-lexical#42]

**Comment by enesbala5** [comment]
Think this looks good enough.. Let me know

![banner](https://github.com/umaranis/svelte-lexical/assets/47826227/a043e42d-8da7-4504-96a4-b58effaa925f)

> 
> Exported everything to this archive; PNG & SVG
> [svelte-lexical.zip](https://github.com/umaranis/svelte-lexical/files/12408292/svelte-lexical.zip)
>

**Comment by umaranis** [comment]
Wow, this is so cool.
Thanks @enesbala5 :)

I will apply on the main page and elsewhere.

**Comment by umaranis** [comment]
logo is added to all the demo applications and the banner is added to the readme.
