### ISSUE TITLE
Importing svelte-lexical causes error

### ISSUE THREAD

**Issue by winterSteve25** [umaranis/svelte-lexical#47]
When importing RichTextComposer and other components provided by `svelte-lexical`, this error is printed in the console

``
index.js:122 Yjs was already imported. This breaks constructor checks and will lead to issues! - https://github.com/yjs/yjs/issues/438``

**Comment by mpreziuso** [comment]
Hey @winterSteve25, see https://github.com/umaranis/svelte-lexical/issues/20 .

**Comment by umaranis** [comment]
Thanks @mpreziuso for the response.

Basically, you need to add yjs package path resolution to `vite.config.ts` (see [here](https://github.com/umaranis/svelte-lexical/commit/6e60373ba3e905c46c0996db7aed84f00934270c))

**Comment by winterSteve25** [comment]
Thank you both very much!
