### ISSUE TITLE
Custom Svelte component content blocks?

### ISSUE THREAD

**Issue by rchrdnsh** [umaranis/svelte-lexical#52]
This seems new and cool and promising :-)

I have been looking around at different editors and am curious about this...

The biggest thing I want to be able to do is to make and offer custom content components to my users...

Is something like that possible with lexical or with your version of lexical?

Any plans on something like that in the future?

Thanks! XD

**Comment by umaranis** [comment]
Hi @rchrdnsh ,
We can have custom components , but they need to implement the svelte-lexical plugin interface. In fact, most of the functionality in the editor is implemented using plugins. Image plugin, Keyword, Hashtag, Horizontal Rule, Table and others are examples of such plugins.

By implementing the plugin interface, we ensure that import/export, undo/redo and other features work for the custom components.
