### ISSUE TITLE
No matching export... fresh pull/test

### ISSUE THREAD

**Issue by maietta** [umaranis/svelte-lexical#53]
I've been looking at this project for a while and finally decided to try it again after several months. Like the last time I tried to use it, it failed miserably and not sure why. Again this time, I feel like i'm the only person having this problem as nobody else mentioned it.

Per instructions:

Cloned project to local machine. `cd demo/playground && npm i && npm run dev`` gets me the following.

```
X [ERROR] No matching export in "node_modules/svelte-lexical/src/core/plugins/Image/ImageNode.css" for import "$createImageNode"

    node_modules/svelte-lexical/src/core/plugins/Image/ImagePlugin.svelte:44:1:
      44 │   $createImageNode as createImageNode,
         ╵   ~~~~~~~~~~~~~~~~

X [ERROR] No matching export in "node_modules/svelte-lexical/src/core/plugins/Image/ImageNode.css" for import "$isImageNode"

    node_modules/svelte-lexical/src/core/plugins/Image/ImagePlugin.svelte:45:1:
      45 │   $isImageNode as isImageNode,
         ╵   ~~~~~~~~~~~~

X [ERROR] No matching export in "node_modules/svelte-lexical/src/core/plugins/Image/ImageNode.css" for import "ImageNode"

    node_modules/svelte-lexical/src/core/plugins/Image/ImagePlugin.svelte:46:1:
      46 │   ImageNode
         ╵   ~~~~~~~~~

X [ERROR] No matching export in "node_modules/svelte-lexical/src/core/plugins/Image/ImageNode.css" for import "ImageNode"

    node_modules/svelte-lexical/src/components/richtext/RichTextComposer.svelte:30:9:
      30 │ import { ImageNode } from '../../core/plugins/Image/ImageNode';
         ╵          ~~~~~~~~~

5:01:59 PM [vite] error while updating dependencies:
node_modules/svelte-lexical/src/components/richtext/RichTextComposer.svelte:30:9: ERROR: No matching export in "node_modules/svelte-lexical/src/core/plugins/Image/ImageNode.css" for import "ImageNode"node_modules/svelte-lexical/src/core/plugins/Image/ImagePlugin.svelte:44:1: ERROR: No matching export in "node_modules/svelte-lexical/src/core/plugins/Image/ImageNode.css" for import "$createImageNode"
node_modules/svelte-lexical/src/core/plugins/Image/ImagePlugin.svelte:45:1: ERROR: No matching export in "node_modules/svelte-lexical/src/core/plugins/Image/ImageNode.css" for import "$isImageNode"
node_modules/svelte-lexical/src/core/plugins/Image/ImagePlugin.svelte:46:1: ERROR: No matching export in "node_modules/svelte-lexical/src/core/plugins/Image/ImageNode.css" for import "ImageNode"
    at failureErrorWithLog (C:\Users\nick\Documents\GitHub\svelte-lexical\demos\playground\node_modules\esbuild\lib\main.js:1639:15)
    at C:\Users\nick\Documents\GitHub\svelte-lexical\demos\playground\node_modules\esbuild\lib\main.js:1051:25
    at C:\Users\nick\Documents\GitHub\svelte-lexical\demos\playground\node_modules\esbuild\lib\main.js:1515:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by maietta** [comment]
Okay, apparently I cannot use `npm` but instead had to use `pnpm`.

This needs to be documented as a requirement. Most people like me may have never heard of "npm workspaces" and thus have no that it means required use of pnpm instead of npm.

**Comment by maietta** [comment]
If I use your template directly, I can get the demo/sveltekit and demo/playground to work.

HOWEVER:

If I setup my project using `pnpm create svelte@latest` method, the original post still stands.

Something about the way you are using Svelte vs SvelteKit setup strategy causes a difference.

**Comment by umaranis** [comment]
Looking into it @maietta , will get back to you

**Comment by maietta** [comment]
Okay thanks! I'm still trying to pin down exactly what's causing this.

**Comment by maietta** [comment]
[I'm chasing a wild goose here, but it seems that this is tied to the issue that the editor is trying to render via SSR mode (default for SvelteKit). However despite the disabling of the SSR mode, I get the same error.

](https://github.com/maietta/svelte-lexical-mre)

**Comment by umaranis** [comment]
Hi @maietta ,

It is caused by the newer version of one of the dependencies. I will narrow it down to the specific dependency and update here.

So, the npm build should also work (at least if we build one of the release tags). The reason it is not working is: we don't have a package lock file for NPM in the project, because of that NPM is fetching newer versions of the packages within the allowed range. We have the package lock file for PNPM, therefore it is only fetching the tested versions.

I removed the '^' symbol from package version numbers in package.json and it resolves the issue for building with NPM.

Next, I will narrow down to the specific dependency which is causing this issue.

**Comment by umaranis** [comment]
This error occurs when all three of the following are true:

- npm package manager is used instead of pnpm
- vite version is higher than 4.3.1
- dev build instead of prod

The root of the problem is: ImageNode.css is fetched instead of ImageNode.ts when 'ImageNode' is imported without extension.

**Comment by maietta** [comment]
I can't begin to imagine how you isolated that. Wow. I spent more hours than I care to admit on it, and I had to walk away and go do something else.

**Comment by maietta** [comment]
While I don't have the ideal solution to fix the problem, the simplest fix was to rename the css file to something else, then update the reference. This resolves the typescript issue. I would prefer to know a better way, but it works and that allows me to move forward.

I've submitted a PR with a quick fix here: https://github.com/umaranis/svelte-lexical/pull/54

If you have a better solution, please feel free to reject my PR in favor of a better solution.

**Comment by umaranis** [comment]
Strange thing is that there are many other plugins which have the same names for css and ts files, but the problem only occurs for ImageNode

Anyways, @maietta's PR should resolve the issue for NPM users.

**Comment by maietta** [comment]
Um... darn it.

https://github.com/umaranis/svelte-lexical/actions/runs/5565229632/jobs/10165429318

![image](https://github.com/umaranis/svelte-lexical/assets/11745020/68948738-b1b4-4f9f-a028-35603eeee34d)

**Comment by umaranis** [comment]
@maietta don't worry it. That particular set of tests were failing even before your PR.

**Comment by maietta** [comment]
> @maietta don't worry it. That particular set of tests were failing even before your PR.

I realized that after i posted, but we could use a version bump. 

Thanks

**Comment by umaranis** [comment]
@maietta new version is published

> > @maietta don't worry it. That particular set of tests were failing even before your PR.
> 
> I realized that after i posted, but we could use a version bump.
> 
> Thanks
