### ISSUE TITLE
Version bump requested.

### ISSUE THREAD

**Issue by maietta** [umaranis/svelte-lexical#55]
Seems the project built, but the test failed. If it's still good, I'd like to include the official library in my project but a version bump will be needed for a new release.

I don't know why the test failed for Firefox, but I suspect this was a fluke.

Regarding my previous PR discussed here: https://github.com/umaranis/svelte-lexical/issues/53

**Comment by umaranis** [comment]
new version 0.3.4 is published @maietta

**Comment by maietta** [comment]
Thank you so much!
