### ISSUE TITLE
Upload inserted images to a backend

### ISSUE THREAD

**Issue by PaddiM8** [umaranis/svelte-lexical#60]
It would be nice to have some way to automatically upload inserted images to a backend and then use the returned URL, if it isn't possible already. Right now it doesn't seem to be possible to paste some types of images as well (when the clipboard data doesn't contain an external url?).

Maybe it could simply be handled by some event with a callback?

**Comment by PaddiM8** [comment]
Ok, I might have a solution that fixes the problem where some images can't be pasted, while also making it possible to replace the URL of pasted images.

In `ImagePlugin`, I dispatch an `insert` event for `INSERT_IMAGE_COMMAND`, that contains the image's `src` and a reference to a function that lets you update the image source. I also added a registerCommand call for `PASTE_COMMAND`, which converts pasted images to base64 in order to make it possible to paste and kind of copied image, and then the same things are done as for `INSERT_IMAGE_COMMAND`.

This is probably what I'm going to use for myself at least, but I could also make PR if anything here is relevant for the official svelte-lexical. Will also think a bit more about the structure.

**Comment by umaranis** [comment]
Hi @PaddiM8 ,

Perhaps this could be added to one of the demos, instead of the svelte-lexical core. Is your code in an open source repo? Can I have a look please?

Thanks.

**Comment by PaddiM8** [comment]
Hi. I made modifications to the core package in my fork to make this possible. It's available here https://github.com/PaddiM8/svelte-lexical/tree/fix-image-paste
