### ISSUE TITLE
No exports condition for Sveltekit v2 (Deprecation Warning)

### ISSUE THREAD

**Issue by Rar9** [umaranis/svelte-lexical#65]
[vite-plugin-svelte] WARNING: The following packages have a svelte field in their package.json but no exports condition for svelte.

svelte-lexical@0.3.4

Please see https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#missing-exports-condition for details.

**Comment by umaranis** [comment]
Hi @Rar9 ,
Which project should I build to see the warning message?

**Comment by Rar9** [comment]
For sveltekit 2 u need to add

"exports": {
        ".": {
            "svelte": "./src/index.js"
        }
    },

**Comment by umaranis** [comment]
It seems to be for the library project i.e. `packages/svelte-lexical`.

I am not getting this warning for any of the projects, probably because of the lower svelte version.

**Comment by Rar9** [comment]
Yes sveltekit 2 was just released.

Did you fix the last package.json pull request i provided? 

U said a test didn't pass.

**Comment by umaranis** [comment]
Several tests are failing with that pull request. I have fixed a few in recent commits. Basically, I have to update one dependency at a time and fix issues that show up.

**Comment by umaranis** [comment]
fixed with 0.4.0
