### ISSUE TITLE
Named export 'registerRichText' not found

### ISSUE THREAD

**Issue by Felixaverlant** [umaranis/svelte-lexical#66]
Hi there,

First of all, thanks for your work!
I wanted to try to add this lib to my current projet that is using sveltekit.

I copy paste the demo sveltekit app (which works locally) but I have the following error on my project : 

```
SyntaxError: [vite] Named export 'registerRichText' not found. The requested module '@lexical/rich-text' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@lexical/rich-text';
const {registerRichText} = pkg;

    at analyzeImportedModDifference (file:///.../node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:50598:19)
    at nodeImport (file:///.../node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:50549:9)
    at async ssrImport (file:///...node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:50444:24)
    at async eval (.../node_modules/svelte-lexical/src/core/plugins/RichTextPlugin.svelte:5:31)
    at async instantiateModule (file:///.../node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:50506:9)
```

The only differences are my deps but have no other leads:
```json
{
"svelte-lexical": "^0.3.4",
"svelte": "^4.2.7",
"@sveltejs/kit": "^2.0.0",
}
```
vs the demo app 
```json
{
"svelte-lexical": "0.3.4",
"svelte": "^3.58.0",
"@sveltejs/kit": "^1.15.8",
}
```

Any idea where I should look into ? I thought SSR might have been the problem but same error when I disable it on the page

**Comment by Felixaverlant** [comment]
downgrading vite version to < 5.0.0 solved my issue

**Comment by enesbala5** [comment]
I don't see how downgrading vite is a solution. I suggest re-opening this issue

**Comment by umaranis** [comment]
Hi @enesbala5 ,

Vite 5 has been supported with the release `0.4.0`. 

Are you still facing this issue?

**Comment by enesbala5** [comment]
Yep, I am getting the following issue:

Error when evaluating SSR module /node_modules/svelte-lexical/dist/core/plugins/PlainTextPlugin.svelte: failed to import "@lexical/plain-text"
|- SyntaxError: [vite] Named export 'registerPlainText' not found. The requested module '@lexical/plain-text' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@lexical/plain-text';
const {registerPlainText} = pkg;

Was this fixed for other people? Thanks in advance for the help

**Comment by umaranis** [comment]
Hi @enesbala5 ,

Could you confirm that you are on the latest version of `svelte-lexical` i.e. `0.4.0`?

Also, your `vite.config.js` should look like this (note `ssr.noExternal`)

```javascript
import {sveltekit} from '@sveltejs/kit/vite';
import {defineConfig} from 'vite';

export default defineConfig({
  plugins: [sveltekit()],
  ssr: {
    noExternal: [/^(lexical|@lexical\/.*)$/],
  },
});
```
