### ISSUE TITLE
Prismjs is causing problems with NPM dev build

### ISSUE THREAD

**Issue by umaranis** [umaranis/svelte-lexical#85]
Prismjs doesn't support ESM which is the likely cause of this issue

**Comment by umaranis** [comment]
Hi @enesbala5 ,

It works with `npm run build` and `npm run preview`, only the dev build is not working. It also works with `pnpm` including dev build.

I am exploring different options to get around this issue.

**Comment by enesbala5** [comment]
Ah okay understood - thank you!
