### ISSUE TITLE
Will lexical table plugin be supported？

### ISSUE THREAD

**Issue by pan2za** [umaranis/svelte-lexical#95]

**Comment by umaranis** [comment]
Hi @pan2za ,
Yes, we plan to support it in the future. 

Are you interested in contributing in development? @Sulkar ([https://github.com/Sulkar](https://github.com/Sulkar)) is also interested in building table plugin.

**Comment by pan2za** [comment]
No, I'm not so familiar with svelte.

**Comment by umaranis** [comment]
Hi @pan2za ,

Table plugin is supported now.

**Comment by Sulkar** [comment]
Perfect thank you very much!
