### ISSUE TITLE
e2e test results are timeout

### ISSUE THREAD

**Issue by pan2za** [umaranis/svelte-lexical#97]
Result: 
 4) [chromium] › e2e\HorizontalRule.spec.mjs:30:3 › HorizontalRule › Can create a horizontal rule and move selection around it

    Test timeout of 150000ms exceeded.

    Error: page.waitForSelector: Test timeout of 150000ms exceeded.
    Call log:
      - waiting for locator('.toolbar-item[aria-label="Insert specialized editor node"]') to be visible

       at utils\index.mjs:539

      537 | export async function click(page, selector, options) {
      538 |   const frame = getPageOrFrame(page);
    > 539 |   await frame.waitForSelector(selector, options);
          |               ^
      540 |   await frame.click(selector, options);
      541 | }
      542 |
Steps to reproduce the issue:
cd demos/playground
1 pnpm run dev
in another console :
1 pnpm test-e2e-chromium

**Comment by pan2za** [comment]
[Playwright Test Report.zip](https://github.com/user-attachments/files/17209441/Playwright.Test.Report.zip)

**Comment by umaranis** [comment]
Hi @pan2za ,

I am not able to reproduce this issue.
I followed the steps to reproduce exactly and get the following:

![image](https://github.com/user-attachments/assets/0ba8e8a8-7e1a-4b4d-919d-73443707489d)
